export { Header } from '../components/Header'
export { Footer } from '../components/Footer'
export { default as Body } from '../components/Body'
export { default as Card } from '../components/Card'
export { default as Shrimmer } from '../components/Shrimmer'