export { Header } from '../components/Header'
export { Footer } from '../components/Footer'
export { default as MainBody } from './MainBody'
export { default as Card } from '../components/Card'
export { default as Shrimmer } from '../components/Shrimmer'
export { default as MainLayout } from '../components/MainLayout'